### ISSUE TITLE
Clean up command calls

### ISSUE THREAD

**Issue by graven** [qubell-bazaar/broadleaf-starter-kit#10]
This is how the syntax for most steps looks today (actual example):

``` yaml
- create-db: # Create database or DemoSite. Here we use serviceCall action, this way we can call additional workflows in submodules
    action: serviceCall
    phase: create-db
    precedingPhases: [ get-env-props ]
    parameters:
        timeout: 600
        service: mysql # correseponded to interface mysql in component main.workflow
        command: db # correseponded to pin mysql.db in component main.workflow
        arguments:
            db-name: "{$.db-name}" # send-command parameter
            db-action: "create"  # send-command parameter
```

In the current version, the same action can be written down with a much shorter syntax:

``` yaml
- create-db: # Create database or DemoSite. Here we use serviceCall action, this way we can call additional workflows in submodules
    action: mysql.db
    precedingPhases: [ get-env-props ]
    parameters:
        commandCallTimeout: 10 minutes
        db-name: "{$.db-name}" # send-command parameter
        db-action: "create"  # send-command parameter
```

Since people are using our manifests as examples, we need to update the command calls to use the cleaner syntax.
